<?php

namespace Database\Seeders;

use App\Services\StudentOnlineRegistrationService;
use App\Services\UserService;
use Illuminate\Database\Seeder;
use App\Services\StudentService;
use App\Services\StudentSessionService;

class StudentSeeder extends Seeder
{
    public function __construct(
        private readonly UserService $userService,
        private readonly StudentService $studentService,
        private readonly StudentSessionService $studentSessionService,
        private readonly StudentOnlineRegistrationService $studentOnlineRegistrationService
    ) {
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $studentsData = [
            [
                'parent_id' => 1,
                'first_name' => 'Abir',
                'last_name' => 'Ahmad',
                'email' => 'abir.ahmad007@gmail.com',
                'birthday' => '1993-08-06',
                'gender' => 'Male',
                'blood_group' => 'A+',
                'religion' => 'Islam',
                'phone' => '01766121212',
                'address' => '123 Main Street',
                'state' => 'Dhaka',
                'country' => 'Bangladesh',
                'register_no' => 'REG12345',
                'password' => '12345678',
                'user_type' => 'Student',
                'class' => rand(1, 2),
                'section' => rand(1, 2),
                'roll' => 1101,
                'group' => rand(1, 3),
                'activities' => 'Activity 1, Activity 2',
                'remarks' => 'Lorem ipsum dolor sit amet.'
            ],
            [
                'parent_id' => 2,
                'first_name' => 'Mahin',
                'last_name' => 'Hossain',
                'email' => 'student@example.com',
                'birthday' => '1993-08-06',
                'gender' => 'Male',
                'blood_group' => 'A+',
                'religion' => 'Islam',
                'phone' => '1234567890',
                'address' => '123 Main Street',
                'state' => 'Dhaka',
                'country' => 'Bangladesh',
                'register_no' => 'REG12345',
                'password' => '12345678',
                'user_type' => 'Student',
                'class' => 1,
                'section' => 1,
                'roll' => 1201,
                'group' => 1,
                'activities' => 'Activity 1, Activity 2',
                'remarks' => 'Lorem ipsum dolor sit amet.'
            ],
            [
                'parent_id' => 2,
                'first_name' => 'Aisha',
                'last_name' => 'Rahman',
                'email' => 'aisha.rahman@example.com',
                'birthday' => '1994-09-12',
                'gender' => 'Female',
                'blood_group' => 'B+',
                'religion' => 'Islam',
                'phone' => '01888',
                'address' => '456 Elm Street',
                'state' => 'Dhaka',
                'country' => 'Bangladesh',
                'register_no' => 'REG12346',
                'password' => 'abcdefg',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(3, 4),
                'roll' => 1102,
                'group' => rand(1, 3),
                'activities' => 'Drawing Club, Music Club',
                'remarks' => 'Diligent and creative student.'
            ],
            [
                'parent_id' => 2,
                'first_name' => 'Sara',
                'last_name' => 'Johnson',
                'email' => 'sara.johnson@example.com',
                'birthday' => '1995-05-15',
                'gender' => 'Female',
                'blood_group' => 'B-',
                'religion' => 'Christianity',
                'phone' => '555-1234',
                'address' => '456 Elm Street',
                'state' => 'New York',
                'country' => 'USA',
                'register_no' => 'REG67890',
                'password' => 'securepass123',
                'user_type' => 'Student',
                'class' => rand(1, 2),
                'section' => rand(1, 2),
                'roll' => 2032,
                'group' => 2,
                'activities' => 'Chess Club, Science Club',
                'remarks' => 'Conscientious student with excellent academic record.'
            ],
            [
                'parent_id' => 3,
                'first_name' => 'Ahmed',
                'last_name' => 'Khan',
                'email' => 'ahmed.khan@example.com',
                'birthday' => '1994-03-20',
                'gender' => 'Male',
                'blood_group' => 'O+',
                'religion' => 'Islam',
                'phone' => '01999',
                'address' => '789 Oak Street',
                'state' => 'Karachi',
                'country' => 'Pakistan',
                'register_no' => 'REG24680',
                'password' => 'p@ssw0rd',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(3, 4),
                'roll' => 1523,
                'group' => rand(1, 3),
                'activities' => 'Football, Debate Club',
                'remarks' => 'Energetic and enthusiastic student.'
            ],
            [
                'parent_id' => 4,
                'first_name' => 'Lina',
                'last_name' => 'Chowdhury',
                'email' => 'lina.chow@example.com',
                'birthday' => '1996-11-02',
                'gender' => 'Female',
                'blood_group' => 'AB-',
                'religion' => 'Hinduism',
                'phone' => '01555',
                'address' => '101 Pine Street',
                'state' => 'Dhaka',
                'country' => 'Bangladesh',
                'register_no' => 'REG13579',
                'password' => 'qwerty123',
                'user_type' => 'Student',
                'class' => 1,
                'section' => rand(1, 2),
                'roll' => 3045,
                'group' => 2,
                'activities' => 'Dance Club, Art Club',
                'remarks' => 'Creative and talented artist.'
            ],
            [
                'parent_id' => 5,
                'first_name' => 'Rahul',
                'last_name' => 'Mehta',
                'email' => 'rahul.mehta@example.com',
                'birthday' => '1995-07-12',
                'gender' => 'Male',
                'blood_group' => 'A-',
                'religion' => 'Hinduism',
                'phone' => '0177102030',
                'address' => '222 Maple Street',
                'state' => 'Mumbai',
                'country' => 'India',
                'register_no' => 'REG97531',
                'password' => 'studentpass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(2, 4),
                'roll' => 2310,
                'group' => rand(1, 3),
                'activities' => 'Cricket, Science Club',
                'remarks' => 'Curious and inquisitive learner.'
            ],
            [
                'parent_id' => 6,
                'first_name' => 'Emily',
                'last_name' => 'Smith',
                'email' => 'emily.smith@example.com',
                'birthday' => '1994-01-28',
                'gender' => 'Female',
                'blood_group' => 'O-',
                'religion' => 'Christianity',
                'phone' => '555-6789',
                'address' => '333 Cedar Street',
                'state' => 'California',
                'country' => 'USA',
                'register_no' => 'REG86420',
                'password' => 'emilypassword',
                'user_type' => 'Student',
                'class' => 1,
                'section' => rand(1, 2),
                'roll' => 1456,
                'group' => 2,
                'activities' => 'Basketball, Music Club',
                'remarks' => 'Talented musician and athlete.'
            ],
            [
                'parent_id' => 7,
                'first_name' => 'MD Sadman',
                'last_name' => 'Shuvo',
                'email' => '01775795045',
                'birthday' => '1993-12-10',
                'gender' => 'Male',
                'blood_group' => 'B+',
                'religion' => 'Islam',
                'phone' => '01688',
                'address' => '444 Oak Street',
                'state' => 'Karachi',
                'country' => 'Pakistan',
                'register_no' => 'REG75319',
                'password' => 'sadman@123',
                'user_type' => 'Student',
                'class' => 1,
                'section' => rand(1, 2),
                'roll' => 2789,
                'group' => rand(1, 3),
                'activities' => 'Football, Debate Club',
                'remarks' => 'Active participant in school events.'
            ],
            [
                'parent_id' => 8,
                'first_name' => 'Aisha',
                'last_name' => 'Malik',
                'email' => 'aisha.malik@example.com',
                'birthday' => '1996-04-18',
                'gender' => 'Female',
                'blood_group' => 'A+',
                'religion' => 'Islam',
                'phone' => '01799',
                'address' => '555 Elm Street',
                'state' => 'Lahore',
                'country' => 'Pakistan',
                'register_no' => 'REG64218',
                'password' => 'aisha786',
                'user_type' => 'Student',
                'class' => 1,
                'section' => rand(1, 2),
                'roll' => 3150,
                'group' => 2,
                'activities' => 'Science Club, Art Club',
                'remarks' => 'Enthusiastic about science and art.'
            ],
            [
                'parent_id' => 9,
                'first_name' => 'Ethan',
                'last_name' => 'Brown',
                'email' => 'ethan.brown@example.com',
                'birthday' => '1994-06-25',
                'gender' => 'Male',
                'blood_group' => 'O+',
                'religion' => 'Christianity',
                'phone' => '555-4321',
                'address' => '777 Maple Street',
                'state' => 'Texas',
                'country' => 'USA',
                'register_no' => 'REG51927',
                'password' => 'ethanpass',
                'user_type' => 'Student',
                'class' => 1,
                'section' => rand(1, 2),
                'roll' => 2698,
                'group' => rand(1, 3),
                'activities' => 'Football, Music Club',
                'remarks' => 'Athletic and musically inclined student.'
            ],
            [
                'parent_id' => 10,
                'first_name' => 'Sophia',
                'last_name' => 'Lee',
                'email' => 'sophia.lee@example.com',
                'birthday' => '1995-09-05',
                'gender' => 'Female',
                'blood_group' => 'AB+',
                'religion' => 'Buddhism',
                'phone' => '01677',
                'address' => '888 Cedar Street',
                'state' => 'Colombo',
                'country' => 'Sri Lanka',
                'register_no' => 'REG73264',
                'password' => 'sophiapass',
                'user_type' => 'Student',
                'class' => 1,
                'section' => rand(1, 2),
                'roll' => 1823,
                'group' => 2,
                'activities' => 'Chess Club, Debate Club',
                'remarks' => 'Intelligent and analytical thinker.'
            ],
            [
                'parent_id' => 11,
                'first_name' => 'Liam',
                'last_name' => 'Johnson',
                'email' => 'liam.johnson@example.com',
                'birthday' => '1994-03-10',
                'gender' => 'Male',
                'blood_group' => 'A-',
                'religion' => 'Christianity',
                'phone' => '555-9876',
                'address' => '111 Pine Street',
                'state' => 'California',
                'country' => 'USA',
                'register_no' => 'REG98765',
                'password' => 'liampass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => 2,
                'roll' => 2101,
                'group' => 2,
                'activities' => 'Basketball, Drama Club',
                'remarks' => 'Talented actor and athlete.'
            ],
            [
                'parent_id' => 12,
                'first_name' => 'Emma',
                'last_name' => 'Davis',
                'email' => 'emma.davis@example.com',
                'birthday' => '1995-06-18',
                'gender' => 'Female',
                'blood_group' => 'B+',
                'religion' => 'Islam',
                'phone' => '01788',
                'address' => '222 Cedar Street',
                'state' => 'Dhaka',
                'country' => 'Bangladesh',
                'register_no' => 'REG11111',
                'password' => 'emmapass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => 2,
                'roll' => 2102,
                'group' => 2,
                'activities' => 'Debate Club, Science Club',
                'remarks' => 'Passionate about science and debating.'
            ],
            [
                'parent_id' => 13,
                'first_name' => 'Oliver',
                'last_name' => 'Smith',
                'email' => 'oliver.smith@example.com',
                'birthday' => '1993-11-28',
                'gender' => 'Male',
                'blood_group' => 'O+',
                'religion' => 'Christianity',
                'phone' => '01699',
                'address' => '333 Maple Street',
                'state' => 'New York',
                'country' => 'USA',
                'register_no' => 'REG22222',
                'password' => 'oliverpass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => 2,
                'roll' => 2103,
                'group' => 2,
                'activities' => 'Football, Music Club',
                'remarks' => 'Talented musician and soccer player.'
            ],
            [
                'parent_id' => 14,
                'first_name' => 'Ava',
                'last_name' => 'Lee',
                'email' => 'ava.lee@example.com',
                'birthday' => '1994-08-22',
                'gender' => 'Female',
                'blood_group' => 'AB-',
                'religion' => 'Hinduism',
                'phone' => '01566',
                'address' => '444 Cedar Street',
                'state' => 'Colombo',
                'country' => 'Sri Lanka',
                'register_no' => 'REG33333',
                'password' => 'avapass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => 2,
                'roll' => 2104,
                'group' => 2,
                'activities' => 'Art Club, Chess Club',
                'remarks' => 'Creative artist and chess player.'
            ],
            [
                'parent_id' => 15,
                'first_name' => 'Noah',
                'last_name' => 'Brown',
                'email' => 'noah.brown@example.com',
                'birthday' => '1996-02-14',
                'gender' => 'Male',
                'blood_group' => 'B+',
                'religion' => 'Islam',
                'phone' => '01777203040',
                'address' => '555 Pine Street',
                'state' => 'Karachi',
                'country' => 'Pakistan',
                'register_no' => 'REG44444',
                'password' => 'noahpass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => 2,
                'roll' => 2105,
                'group' => 2,
                'activities' => 'Cricket, Science Club',
                'remarks' => 'Enthusiastic about scientific experiments.'
            ],
            [
                'parent_id' => 16,
                'first_name' => 'Isabella',
                'last_name' => 'Garcia',
                'email' => 'isabella.garcia@example.com',
                'birthday' => '1995-12-05',
                'gender' => 'Female',
                'blood_group' => 'A+',
                'religion' => 'Christianity',
                'phone' => '01711287810',
                'address' => '666 Elm Street',
                'state' => 'California',
                'country' => 'USA',
                'register_no' => 'REG55555',
                'password' => 'isabellapass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => 2,
                'roll' => 2106,
                'group' => 2,
                'activities' => 'Drama Club, Music Club',
                'remarks' => 'Talented singer and actor.'
            ],
            [
                'parent_id' => 17,
                'first_name' => 'William',
                'last_name' => 'Smith',
                'email' => 'william.smith@example.com',
                'birthday' => '1993-09-30',
                'gender' => 'Male',
                'blood_group' => 'O+',
                'religion' => 'Christianity',
                'phone' => '01988',
                'address' => '777 Cedar Street',
                'state' => 'Texas',
                'country' => 'USA',
                'register_no' => 'REG66666',
                'password' => 'williampass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => 2,
                'roll' => 2107,
                'group' => 2,
                'activities' => 'Basketball, Science Club',
                'remarks' => 'Dedicated to basketball and scientific discoveries.'
            ],
            [
                'parent_id' => 18,
                'first_name' => 'Sophie',
                'last_name' => 'Wang',
                'email' => 'sophie.wang@example.com',
                'birthday' => '1994-07-28',
                'gender' => 'Female',
                'blood_group' => 'B-',
                'religion' => 'Buddhism',
                'phone' => '01666',
                'address' => '888 Pine Street',
                'state' => 'Colombo',
                'country' => 'Sri Lanka',
                'register_no' => 'REG77777',
                'password' => 'sophiepass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => 2,
                'roll' => 2108,
                'group' => 2,
                'activities' => 'Chess Club, Art Club',
                'remarks' => 'Strategic chess player and skilled artist.'
            ],
            [
                'parent_id' => 19,
                'first_name' => 'Elijah',
                'last_name' => 'Martinez',
                'email' => 'elijah.martinez@example.com',
                'birthday' => '1996-01-15',
                'gender' => 'Male',
                'blood_group' => 'A-',
                'religion' => 'Christianity',
                'phone' => '555-5678',
                'address' => '999 Elm Street',
                'state' => 'California',
                'country' => 'USA',
                'register_no' => 'REG88888',
                'password' => 'elijahpass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => 2,
                'roll' => 2109,
                'group' => 2,
                'activities' => 'Football, Debate Club',
                'remarks' => 'Passionate about football and debates.'
            ],
            [
                'parent_id' => 20,
                'first_name' => 'Mia',
                'last_name' => 'Nguyen',
                'email' => 'mia.nguyen@example.com',
                'birthday' => '1995-04-09',
                'gender' => 'Female',
                'blood_group' => 'B+',
                'religion' => 'Buddhism',
                'phone' => '01655',
                'address' => '111 Cedar Street',
                'state' => 'Colombo',
                'country' => 'Sri Lanka',
                'register_no' => 'REG99999',
                'password' => 'miapass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => 2,
                'roll' => 2110,
                'group' => 2,
                'activities' => 'Dance Club, Art Club',
                'remarks' => 'Talented dancer and artist.'
            ],
            [
                'parent_id' => 21,
                'first_name' => 'Jackson',
                'last_name' => 'Wilson',
                'email' => 'jackson.wilson@example.com',
                'birthday' => '1996-02-20',
                'gender' => 'Male',
                'blood_group' => 'A+',
                'religion' => 'Christianity',
                'phone' => '555-1111',
                'address' => '111 Elm Street',
                'state' => 'California',
                'country' => 'USA',
                'register_no' => 'REG11111',
                'password' => 'jacksonpass',
                'user_type' => 'Student',
                'class' => 1,
                'section' => rand(1, 2),
                'roll' => rand(2001, 3000),
                'group' => rand(1, 3),
                'activities' => 'Football, Science Club',
                'remarks' => 'Enthusiastic football player and science enthusiast.'
            ],
            [
                'parent_id' => 22,
                'first_name' => 'Grace',
                'last_name' => 'Anderson',
                'email' => 'grace.anderson@example.com',
                'birthday' => '1995-07-12',
                'gender' => 'Female',
                'blood_group' => 'B-',
                'religion' => 'Christianity',
                'phone' => '555-2222',
                'address' => '222 Cedar Street',
                'state' => 'New York',
                'country' => 'USA',
                'register_no' => 'REG22222',
                'password' => 'gracepass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(3, 4),
                'roll' => rand(2001, 3000),
                'group' => rand(1, 3),
                'activities' => 'Art Club, Music Club',
                'remarks' => 'Talented artist and musician.'
            ],
            [
                'parent_id' => 23,
                'first_name' => 'Lucas',
                'last_name' => 'Clark',
                'email' => 'lucas.clark@example.com',
                'birthday' => '1994-09-05',
                'gender' => 'Male',
                'blood_group' => 'O+',
                'religion' => 'Christianity',
                'phone' => '555-3333',
                'address' => '333 Pine Street',
                'state' => 'California',
                'country' => 'USA',
                'register_no' => 'REG33333',
                'password' => 'lucaspass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(3, 4),
                'roll' => rand(2001, 3000),
                'group' => rand(1, 3),
                'activities' => 'Basketball, Drama Club',
                'remarks' => 'Skilled basketball player and actor.'
            ],
            [
                'parent_id' => 24,
                'first_name' => 'Aria',
                'last_name' => 'Hill',
                'email' => 'aria.hill@example.com',
                'birthday' => '1996-03-25',
                'gender' => 'Female',
                'blood_group' => 'A-',
                'religion' => 'Islam',
                'phone' => '555-4444',
                'address' => '444 Cedar Street',
                'state' => 'Dhaka',
                'country' => 'Bangladesh',
                'register_no' => 'REG44444',
                'password' => 'ariapass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(3, 4),
                'roll' => rand(2001, 3000),
                'group' => rand(1, 3),
                'activities' => 'Dance Club, Science Club',
                'remarks' => 'Passionate dancer and science lover.'
            ],
            [
                'parent_id' => 25,
                'first_name' => 'Henry',
                'last_name' => 'Young',
                'email' => 'henry.young@example.com',
                'birthday' => '1995-11-15',
                'gender' => 'Male',
                'blood_group' => 'B+',
                'religion' => 'Hinduism',
                'phone' => '555-5555',
                'address' => '555 Elm Street',
                'state' => 'Mumbai',
                'country' => 'India',
                'register_no' => 'REG55555',
                'password' => 'henrypass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(3, 4),
                'roll' => rand(2001, 3000),
                'group' => rand(1, 3),
                'activities' => 'Cricket, Art Club',
                'remarks' => 'Talented cricketer and artist.'
            ],
            [
                'parent_id' => 26,
                'first_name' => 'Ella',
                'last_name' => 'Baker',
                'email' => 'ella.baker@example.com',
                'birthday' => '1994-04-10',
                'gender' => 'Female',
                'blood_group' => 'A+',
                'religion' => 'Islam',
                'phone' => '555-6666',
                'address' => '666 Cedar Street',
                'state' => 'Karachi',
                'country' => 'Pakistan',
                'register_no' => 'REG66666',
                'password' => 'ellapass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(3, 4),
                'roll' => rand(2001, 3000),
                'group' => rand(1, 3),
                'activities' => 'Music Club, Science Club',
                'remarks' => 'Talented musician and science enthusiast.'
            ],
            [
                'parent_id' => 27,
                'first_name' => 'Leo',
                'last_name' => 'Parker',
                'email' => 'leo.parker@example.com',
                'birthday' => '1993-12-18',
                'gender' => 'Male',
                'blood_group' => 'O-',
                'religion' => 'Christianity',
                'phone' => '555-7777',
                'address' => '777 Pine Street',
                'state' => 'California',
                'country' => 'USA',
                'register_no' => 'REG77777',
                'password' => 'leopass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(3, 4),
                'roll' => rand(2001, 3000),
                'group' => rand(1, 3),
                'activities' => 'Basketball, Drama Club',
                'remarks' => 'Talented actor and basketball player.'
            ],
            [
                'parent_id' => 28,
                'first_name' => 'Scarlett',
                'last_name' => 'Hayes',
                'email' => 'scarlett.hayes@example.com',
                'birthday' => '1996-01-23',
                'gender' => 'Female',
                'blood_group' => 'B+',
                'religion' => 'Christianity',
                'phone' => '555-8888',
                'address' => '888 Cedar Street',
                'state' => 'Texas',
                'country' => 'USA',
                'register_no' => 'REG88888',
                'password' => 'scarlettpass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(3, 4),
                'roll' => rand(2001, 3000),
                'group' => rand(1, 3),
                'activities' => 'Dance Club, Art Club',
                'remarks' => 'Passionate dancer and skilled artist.'
            ],
            [
                'parent_id' => 29,
                'first_name' => 'Jack',
                'last_name' => 'Ward',
                'email' => 'jack.ward@example.com',
                'birthday' => '1995-05-30',
                'gender' => 'Male',
                'blood_group' => 'O+',
                'religion' => 'Hinduism',
                'phone' => '555-9999',
                'address' => '999 Elm Street',
                'state' => 'Mumbai',
                'country' => 'India',
                'register_no' => 'REG99999',
                'password' => 'jackpass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(3, 4),
                'roll' => rand(2001, 3000),
                'group' => rand(1, 3),
                'activities' => 'Cricket, Music Club',
                'remarks' => 'Talented cricketer and musician.'
            ],
            [
                'parent_id' => 30,
                'first_name' => 'Chloe',
                'last_name' => 'Carter',
                'email' => 'chloe.carter@example.com',
                'birthday' => '1996-06-14',
                'gender' => 'Female',
                'blood_group' => 'A-',
                'religion' => 'Islam',
                'phone' => '555-1010',
                'address' => '1010 Pine Street',
                'state' => 'Karachi',
                'country' => 'Pakistan',
                'register_no' => 'REG10101',
                'password' => 'chloepass',
                'user_type' => 'Student',
                'class' => 2,
                'section' => rand(3, 4),
                'roll' => rand(2001, 3000),
                'group' => rand(1, 3),
                'activities' => 'Dance Club, Science Club',
                'remarks' => 'Passionate dancer and science enthusiast.'
            ]
        ];

        foreach ($studentsData as $studentData) {
            // $user = $this->userService->createOrUpdateUser($studentData);

            // $studentDataOnly = [
            //     'user_id' => $user->id,
            //     'parent_id' => $studentData['parent_id'],
            //     'first_name' => $studentData['first_name'],
            //     'last_name' => $studentData['last_name'],
            //     'birthday' => $studentData['birthday'],
            //     'gender' => $studentData['gender'],
            //     'blood_group' => $studentData['blood_group'],
            //     'religion' => $studentData['religion'],
            //     'phone' => $studentData['phone'],
            //     'address' => $studentData['address'],
            //     'state' => $studentData['state'],
            //     'country' => $studentData['country'],
            //     'register_no' => $studentData['register_no'],
            //     'group' => $studentData['group'],
            //     'activities' => $studentData['activities'],
            //     'remarks' => $studentData['remarks'] ?? null,
            // ];

            // $student = $this->studentService->createStudent($studentDataOnly, $user->id);

            // $sessionCreateData = [
            //     'session_id' => intval(get_option('academic_year')),
            //     'student_id' => intval($student->id),
            //     'class_id' => intval($studentData['class']),
            //     'section_id' => intval($studentData['section']),
            //     'roll' => intval($studentData['roll'])
            // ];

            // $this->studentSessionService->createStudentSession($sessionCreateData);

            // keep only some data.
            $studentDataForOnlineRegistration = [
                'first_name' => $studentData['first_name'],
                'last_name' => $studentData['last_name'],
                'birthday' => $studentData['birthday'],
                'gender' => 'Male',
                'blood_group' => $studentData['blood_group'],
                'religion' => $studentData['religion'],
                'phone' => $studentData['phone'],
                'class_id' => 1,
                'group_id' => 1,
                'roll' => rand(200001, 300000),
                'information_sent_to_phone' => rand(11111111111, 99999999999),
                'session_id' => 1,
                'section_id' => 1,

                // For some testimonial.
                'hsc_reg' => rand(200001, 300000),
                'hsc_roll' => rand(200001, 300000),
                'hsc_gpa' => rand(3, 5),
                'hsc_session' => '2023-2024',
            ];

            $this->studentOnlineRegistrationService->createStudentOnlineRegistration(
                $studentDataForOnlineRegistration
            );
        }
    }
}
