<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('users')->insert([
			[
				'id' => 1,
				'role_id' => 0,
				'name' => 'Super Admin',
				'email' => 'nmdc@admin.com',
				'password' => bcrypt('ndcm1234'),
				'password_static' => 'ndcm1234',
				'user_type' => 'Admin',
				'phone' => '00000000000',
				'status' => 1,
				'image' => 'profile.png',
				'facebook' => null,
				'twitter' => null,
				'linkedin' => null,
				'google_plus' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id' => 2,
				'role_id' => 0,
				'name' => 'Teacher',
				'email' => 'teacher@example.com',
				'password' => bcrypt('12345678'),
				'password_static' => '12345678',
				'user_type' => 'Teacher',
				'phone' => '00000000001',
				'status' => 1,
				'image' => 'profile.png',
				'facebook' => null,
				'twitter' => null,
				'linkedin' => null,
				'google_plus' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id' => 3,
				'role_id' => 0,
				'name' => 'Fr. Thadeus Hembrom, CSC',
				'email' => 'thadeus@gmail.com',
				'password' => bcrypt('12345678'),
				'password_static' => '12345678',
				'user_type' => 'Teacher',
				'phone' => '00000000002',
				'status' => 1,
				'image' => 'teachers/principal.jpg',
				'facebook' => null,
				'twitter' => null,
				'linkedin' => null,
				'google_plus' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id' => 4,
				'role_id' => 0,
				'name' => 'Fr. Hubert Palma',
				'email' => 'hubert@gmail.com',
				'password' => bcrypt('12345678'),
				'password_static' => '12345678',
				'user_type' => 'Teacher',
				'phone' => '00000000003',
				'status' => 1,
				'image' => 'teachers/hubert.jpg',
				'facebook' => null,
				'twitter' => null,
				'linkedin' => null,
				'google_plus' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id' => 5,
				'role_id' => 0,
				'name' => 'Staff 01',
				'email' => 'staff01@example.com',
				'password' => bcrypt('12345678'),
				'password_static' => '12345678',
				'user_type' => 'Staff',
				'phone' => '01840416216',
				'status' => 1,
				'image' => 'profile.png',
				'facebook' => null,
				'twitter' => null,
				'linkedin' => null,
				'google_plus' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id' => 6,
				'role_id' => 0,
				'name' => 'Guardian One',
				'email' => 'guardian-one@gmail.com',
				'password' => bcrypt('12345678'),
				'password_static' => '12345678',
				'user_type' => 'Parent',
				'phone' => '00000000005',
				'status' => 1,
				'image' => 'profile.png',
				'facebook' => null,
				'twitter' => null,
				'linkedin' => null,
				'google_plus' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id' => 7,
				'role_id' => 0,
				'name' => 'Guardian Two',
				'email' => 'guardian-two@gmail.com',
				'password' => bcrypt('12345678'),
				'password_static' => '12345678',
				'user_type' => 'Parent',
				'phone' => '00000000006',
				'status' => 1,
				'image' => 'profile.png',
				'facebook' => null,
				'twitter' => null,
				'linkedin' => null,
				'google_plus' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
		]);
	}
}
